import type { Metadata } from "next";
import { Kosugi_Maru } from 'next/font/google';
import "./globals.css";
import { GitHubUser, fetchGithubUser } from "./types";
import Header from "./components/header";
import Footer from "./components/footer";

const kosugiMaru = Kosugi_Maru({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap', 
});

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "GitHub Pages",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico"
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const githubUser: GitHubUser = await fetchGithubUser();
  return (
    <html lang="en">
    <body className={`${kosugiMaru.className} bg-white text-black antialiased dark:bg-gray-950 dark:text-white`}>
      <section className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
        <Header githubUser={githubUser} />
        {children}
        <Footer githubUser={githubUser} />
        </section>
      </body>
    </html>
  );
}
